export const dummyPaymentsHistory = [
  {
    id: "728ed52f",
    transaction: "basic subscription",
    amount: 69,
    date: "11/04/2024",
    status: "accepted",
    account: {
      type: "Visa",
      number: "3304",
      icon: "/icons/visa.svg",
      expires: "24/10",
    },
  },
  {
    id: "729fd63g",
    transaction: "premium subscription",
    amount: 102,
    date: "11/02/2024",
    status: "accepted",
    account: {
      type: "Mastercard",
      number: "4029",
      icon: "/icons/mastercard.svg",
      expires: "24/10",
    },
  },
  {
    id: "730ge74h",
    transaction: "software license",
    amount: 49,
    date: "10/29/2024",
    status: "pending",
    account: {
      type: "Visa",
      number: "7521",
      icon: "/icons/visa.svg",
      expires: "25/03",
    },
  },
  {
    id: "731hf85i",
    transaction: "cloud storage",
    amount: 15,
    date: "10/27/2024",
    status: "accepted",
    account: {
      type: "Mastercard",
      number: "6643",
      icon: "/icons/mastercard.svg",
      expires: "25/06",
    },
  },
  {
    id: "732ig96j",
    transaction: "marketing tools",
    amount: 199,
    date: "10/25/2024",
    status: "rejected",
    account: {
      type: "Visa",
      number: "8832",
      icon: "/icons/visa.svg",
      expires: "24/12",
    },
  },
  {
    id: "733jh07k",
    transaction: "design software",
    amount: 89,
    date: "10/23/2024",
    status: "accepted",
    account: {
      type: "Mastercard",
      number: "2217",
      icon: "/icons/mastercard.svg",
      expires: "25/09",
    },
  },
  {
    id: "743ts07u",
    transaction: "crm software",
    amount: 179,
    date: "10/03/2024",
    status: "rejected",
    account: {
      type: "Mastercard",
      number: "4418",
      icon: "/icons/mastercard.svg",
      expires: "25/03",
    },
  },
  {
    id: "744ut18v",
    transaction: "email marketing",
    amount: 49,
    date: "10/01/2024",
    status: "accepted",
    account: {
      type: "Visa",
      number: "9923",
      icon: "/icons/visa.svg",
      expires: "24/06",
    },
  },
  {
    id: "745vu29w",
    transaction: "project tracking",
    amount: 69,
    date: "09/29/2024",
    status: "pending",
    account: {
      type: "Mastercard",
      number: "6612",
      icon: "/icons/mastercard.svg",
      expires: "25/05",
    },
  },
  {
    id: "746vw30x",
    transaction: "customer support",
    amount: 39,
    date: "09/27/2024",
    status: "accepted",
    account: {
      type: "Visa",
      number: "7741",
      icon: "/icons/visa.svg",
      expires: "24/10",
    },
  },
  {
    id: "747wx41y",
    transaction: "team collaboration",
    amount: 119,
    date: "09/25/2024",
    status: "rejected",
    account: {
      type: "Mastercard",
      number: "5526",
      icon: "/icons/mastercard.svg",
      expires: "25/02",
    },
  },
  {
    id: "748xy52z",
    transaction: "data visualization",
    amount: 89,
    date: "09/23/2024",
    status: "accepted",
    account: {
      type: "Visa",
      number: "3315",
      icon: "/icons/visa.svg",
      expires: "24/09",
    },
  },
  {
    id: "749yz63a",
    transaction: "network monitoring",
    amount: 199,
    date: "09/21/2024",
    status: "pending",
    account: {
      type: "Mastercard",
      number: "9988",
      icon: "/icons/mastercard.svg",
      expires: "25/04",
    },
  },
  {
    id: "734kj18l",
    transaction: "project management",
    amount: 39,
    date: "10/21/2024",
    status: "pending",
    account: {
      type: "Visa",
      number: "5601",
      icon: "/icons/visa.svg",
      expires: "24/11",
    },
  },
  {
    id: "735lk29m",
    transaction: "analytics platform",
    amount: 129,
    date: "10/19/2024",
    status: "accepted",
    account: {
      type: "Mastercard",
      number: "9914",
      icon: "/icons/mastercard.svg",
      expires: "25/02",
    },
  },
  {
    id: "736ml30n",
    transaction: "communication tool",
    amount: 25,
    date: "10/17/2024",
    status: "accepted",
    account: {
      type: "Visa",
      number: "6653",
      icon: "/icons/visa.svg",
      expires: "24/08",
    },
  },
  {
    id: "737nm41o",
    transaction: "security service",
    amount: 79,
    date: "10/15/2024",
    status: "pending",
    account: {
      type: "Mastercard",
      number: "4401",
      icon: "/icons/mastercard.svg",
      expires: "25/05",
    },
  },
  {
    id: "738on52p",
    transaction: "hosting service",
    amount: 59,
    date: "10/13/2024",
    status: "accepted",
    account: {
      type: "Visa",
      number: "3312",
      icon: "/icons/visa.svg",
      expires: "24/09",
    },
  },
  {
    id: "739po63q",
    transaction: "productivity suite",
    amount: 149,
    date: "10/11/2024",
    status: "rejected",
    account: {
      type: "Mastercard",
      number: "7725",
      icon: "/icons/mastercard.svg",
      expires: "25/01",
    },
  },
  {
    id: "740qp74r",
    transaction: "design assets",
    amount: 29,
    date: "10/09/2024",
    status: "accepted",
    account: {
      type: "Visa",
      number: "5542",
      icon: "/icons/visa.svg",
      expires: "24/07",
    },
  },
  {
    id: "741rq85s",
    transaction: "ai tools",
    amount: 249,
    date: "10/07/2024",
    status: "pending",
    account: {
      type: "Mastercard",
      number: "8877",
      icon: "/icons/mastercard.svg",
      expires: "25/04",
    },
  },
  {
    id: "742sr96t",
    transaction: "development platform",
    amount: 99,
    date: "10/05/2024",
    status: "accepted",
    account: {
      type: "Visa",
      number: "2206",
      icon: "/icons/visa.svg",
      expires: "24/12",
    },
  },
  {
    id: "743ts07u",
    transaction: "crm software",
    amount: 179,
    date: "10/03/2024",
    status: "rejected",
    account: {
      type: "Mastercard",
      number: "4418",
      icon: "/icons/mastercard.svg",
      expires: "25/03",
    },
  },
  {
    id: "744ut18v",
    transaction: "email marketing",
    amount: 49,
    date: "10/01/2024",
    status: "accepted",
    account: {
      type: "Visa",
      number: "9923",
      icon: "/icons/visa.svg",
      expires: "24/06",
    },
  },
  {
    id: "745vu29w",
    transaction: "project tracking",
    amount: 69,
    date: "09/29/2024",
    status: "pending",
    account: {
      type: "Mastercard",
      number: "6612",
      icon: "/icons/mastercard.svg",
      expires: "25/05",
    },
  },
  {
    id: "746vw30x",
    transaction: "customer support",
    amount: 39,
    date: "09/27/2024",
    status: "accepted",
    account: {
      type: "Visa",
      number: "7741",
      icon: "/icons/visa.svg",
      expires: "24/10",
    },
  },
  {
    id: "747wx41y",
    transaction: "team collaboration",
    amount: 119,
    date: "09/25/2024",
    status: "rejected",
    account: {
      type: "Mastercard",
      number: "5526",
      icon: "/icons/mastercard.svg",
      expires: "25/02",
    },
  },
  {
    id: "748xy52z",
    transaction: "data visualization",
    amount: 89,
    date: "09/23/2024",
    status: "accepted",
    account: {
      type: "Visa",
      number: "3315",
      icon: "/icons/visa.svg",
      expires: "24/09",
    },
  },
  {
    id: "749yz63a",
    transaction: "network monitoring",
    amount: 199,
    date: "09/21/2024",
    status: "pending",
    account: {
      type: "Mastercard",
      number: "9988",
      icon: "/icons/mastercard.svg",
      expires: "25/04",
    },
  },

  {
    id: "728ed52f",
    transaction: "basic subscription",
    amount: 69,
    date: "11/04/2024",
    status: "accepted",
    account: {
      type: "Visa",
      number: "3304",
      icon: "/icons/visa.svg",
      expires: "24/10",
    },
  },
  {
    id: "729fd63g",
    transaction: "premium subscription",
    amount: 102,
    date: "11/02/2024",
    status: "accepted",
    account: {
      type: "Mastercard",
      number: "4029",
      icon: "/icons/mastercard.svg",
      expires: "24/10",
    },
  },
  {
    id: "730ge74h",
    transaction: "software license",
    amount: 49,
    date: "10/29/2024",
    status: "pending",
    account: {
      type: "Visa",
      number: "7521",
      icon: "/icons/visa.svg",
      expires: "25/03",
    },
  },
  {
    id: "731hf85i",
    transaction: "cloud storage",
    amount: 15,
    date: "10/27/2024",
    status: "accepted",
    account: {
      type: "Mastercard",
      number: "6643",
      icon: "/icons/mastercard.svg",
      expires: "25/06",
    },
  },
  {
    id: "732ig96j",
    transaction: "marketing tools",
    amount: 199,
    date: "10/25/2024",
    status: "rejected",
    account: {
      type: "Visa",
      number: "8832",
      icon: "/icons/visa.svg",
      expires: "24/12",
    },
  },
  {
    id: "733jh07k",
    transaction: "design software",
    amount: 89,
    date: "10/23/2024",
    status: "accepted",
    account: {
      type: "Mastercard",
      number: "2217",
      icon: "/icons/mastercard.svg",
      expires: "25/09",
    },
  },
  {
    id: "734kj18l",
    transaction: "project management",
    amount: 39,
    date: "10/21/2024",
    status: "pending",
    account: {
      type: "Visa",
      number: "5601",
      icon: "/icons/visa.svg",
      expires: "24/11",
    },
  },
  {
    id: "735lk29m",
    transaction: "analytics platform",
    amount: 129,
    date: "10/19/2024",
    status: "accepted",
    account: {
      type: "Mastercard",
      number: "9914",
      icon: "/icons/mastercard.svg",
      expires: "25/02",
    },
  },
  {
    id: "736ml30n",
    transaction: "communication tool",
    amount: 25,
    date: "10/17/2024",
    status: "accepted",
    account: {
      type: "Visa",
      number: "6653",
      icon: "/icons/visa.svg",
      expires: "24/08",
    },
  },
  {
    id: "737nm41o",
    transaction: "security service",
    amount: 79,
    date: "10/15/2024",
    status: "pending",
    account: {
      type: "Mastercard",
      number: "4401",
      icon: "/icons/mastercard.svg",
      expires: "25/05",
    },
  },
  {
    id: "738on52p",
    transaction: "hosting service",
    amount: 59,
    date: "10/13/2024",
    status: "accepted",
    account: {
      type: "Visa",
      number: "3312",
      icon: "/icons/visa.svg",
      expires: "24/09",
    },
  },
  {
    id: "739po63q",
    transaction: "productivity suite",
    amount: 149,
    date: "10/11/2024",
    status: "rejected",
    account: {
      type: "Mastercard",
      number: "7725",
      icon: "/icons/mastercard.svg",
      expires: "25/01",
    },
  },
];
